export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_LOAD_SUCCESS = "LOGIN_LOAD_SUCCESS";
export const LOGIN_LOAD_FAIL = "LOGIN_LOAD_FAIL";

export const COMPANIES_LOADING = "COMPANIES_LOADING";
export const COMPANIES_LOAD_SUCCESS = "COMPANIES_LOAD_SUCCESS";
export const COMPANIES_LOAD_FAIL = "COMPANIES_LOAD_FAIL";

export const LEADS_LOADING = "LEADS_LOADING";
export const LEADS_LOAD_SUCCESS = "LEADS_LOAD_SUCCESS";
export const LEADS_LOAD_FAIL = "LEADS_LOAD_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
